security:
  jwt:
    key-store: classpath:mystore.keystore
    key-store-password: RiNgO2785
    key-pair-alias: spring_store
    key-pair-password: RiNgO2785
    public-key: classpath:public.txt